const defaultSEOConfig = {
    title: "Saniiro App",
    description: "Generated by create next app",
    openGraph: {
      type: "website",
      locale: "en_IE",
      url: "https://yourwebsite.com/",
      site_name: "Saniiro App",
    },
  };
  
  export default defaultSEOConfig;
  