import ProviderWrapper from "@/components/ProviderWreper";
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Saniiro App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="/bolt.min.js" strategy="beforeInteractive" />
        <link
          href="https://fonts.googleapis.com/css2?family=Prompt&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ProviderWrapper>
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}

// "use client";
// import { DataProvider } from "@components/context/Authcontext";
// import "./globals.css";
// import { ThemeProvider, createTheme } from "@mui/material/styles";
// import { DefaultSeo } from "next-seo";
// import defaultSEOConfig from "@/next-seo.config";

// export default function RootLayout({ children }) {
//   const theme = createTheme({
//     breakpoints: {
//       values: {
//         xs: 0,
//         sm: 314,
//         smm: 530,
//         md: 768,
//         lg: 1024,
//         xl: 1220,
//         xll: 1440,
//         xxl: 1600,
//       },
//     },
//   });

//   return (
//     <html lang="en">
//       <head>
//         <DefaultSeo {...defaultSEOConfig} />
//       </head>
//       <ThemeProvider theme={theme}>
//         <DataProvider>
//           <body>{children}</body>
//         </DataProvider>
//       </ThemeProvider>
//     </html>
//   );
// }
