import ThemeWrapper from "@/components/ThemeWrapper";
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Saniiro App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="/bolt.min.js" strategy="beforeInteractive" />
        <link
          href="https://fonts.googleapis.com/css2?family=Prompt&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ThemeWrapper>
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}

